
export const models = [
    //     { name: 'Hydrological Model.gaml|Run', code: 'Toy Models/Flood Simulation/models/Hydrological Model.gaml|Run' },

    // { name: 'Continuous Move.gaml|main', code: 'Toy Models/Evacuation/models/Continuous Move.gaml|main' },
    // { name: 'Model 05.gaml|road_traffic', code: 'Tutorials/Road Traffic/models/Model 05.gaml|road_traffic' },

    // { name: 'Clean Line Network.gaml|clean_network', code: 'Data/Data Cleaning/models/Clean Line Network.gaml|clean_network' },
    // { name: 'Save Graphs.gaml|main', code: 'Data/Data Exportation/models/Save Graphs.gaml|main' },
    // { name: 'Save to ASC.gaml|main', code: 'Data/Data Exportation/models/Save to ASC.gaml|main' },
    // { name: 'Save to CSV.gaml|main', code: 'Data/Data Exportation/models/Save to CSV.gaml|main' },
    // { name: 'Save to GeoJson.gaml|main', code: 'Data/Data Exportation/models/Save to GeoJson.gaml|main' },
    // { name: 'Save to Geotiff.gaml|main', code: 'Data/Data Exportation/models/Save to Geotiff.gaml|main' },
    // { name: 'Save to KML.gaml|exportkml', code: 'Data/Data Exportation/models/Save to KML.gaml|exportkml' },
    // { name: 'Save to PNG.gaml|main', code: 'Data/Data Exportation/models/Save to PNG.gaml|main' },
    // { name: 'Save to SHP.gaml|main', code: 'Data/Data Exportation/models/Save to SHP.gaml|main' },
    // { name: 'Save to Text.gaml|main', code: 'Data/Data Exportation/models/Save to Text.gaml|main' },
    // { name: '3D shapefile Loading.gaml|display_shape', code: 'Data/Data Importation/models/3D shapefile Loading.gaml|display_shape' },
    // { name: 'ASC File Import.gaml|gridloading', code: 'Data/Data Importation/models/ASC File Import.gaml|gridloading' },
    // { name: 'BingMap Image Import.gaml|Display', code: 'Data/Data Importation/models/BingMap Image Import.gaml|Display' },
    // { name: 'Contour Lines.gaml|contour_lines_import', code: 'Data/Data Importation/models/Contour Lines.gaml|contour_lines_import' },
    // { name: 'CSV Agents.gaml|main', code: 'Data/Data Importation/models/CSV Agents.gaml|main' },
    // { name: 'CSV File Import.gaml|main', code: 'Data/Data Importation/models/CSV File Import.gaml|main' },
    // { name: 'DXF File Import.gaml|DXFAgents', code: 'Data/Data Importation/models/DXF File Import.gaml|DXFAgents' },
    // { name: 'GEOJSON File Import.gaml|Display', code: 'Data/Data Importation/models/GEOJSON File Import.gaml|Display' },
    // { name: 'GEOTIFF File Import.gaml|show_example', code: 'Data/Data Importation/models/GEOTIFF File Import.gaml|show_example' },
    // { name: 'GIF File Loading.gaml|Ripples and Fish', code: 'Data/Data Importation/models/GIF File Loading.gaml|Ripples and Fish' },
    // { name: 'GMLFILE Import.gaml|GIS_agentification', code: 'Data/Data Importation/models/GMLFILE Import.gaml|GIS_agentification' },
    // { name: 'Graph Importation.gaml|import_graph', code: 'Data/Data Importation/models/Graph Importation.gaml|import_graph' },
    // { name: 'Grid DEM.gaml|Comparison', code: 'Data/Data Importation/models/Grid DEM.gaml|Comparison' },
    // { name: 'Image vectorization.gaml|Vectorize', code: 'Data/Data Importation/models/Image vectorization.gaml|Vectorize' },
    // { name: 'JSON File Import.gaml|Display', code: 'Data/Data Importation/models/JSON File Import.gaml|Display' },
    // { name: 'MapQuest Image Import.gaml|Display', code: 'Data/Data Importation/models/MapQuest Image Import.gaml|Display' },
    // { name: 'Multiple Raster Files Import.gaml|importationraster', code: 'Data/Data Importation/models/Multiple Raster Files Import.gaml|importationraster' },
    // { name: 'OBJ file drawing.gaml|Display', code: 'Data/Data Importation/models/OBJ file drawing.gaml|Display' },
    // { name: 'OBJ file loading.gaml|Display', code: 'Data/Data Importation/models/OBJ file loading.gaml|Display' },
    // { name: 'OSM File Import.gaml|Load OSM', code: 'Data/Data Importation/models/OSM File Import.gaml|Load OSM' },
    // { name: 'PNG Icons.gaml|Icons', code: 'Data/Data Importation/models/PNG Icons.gaml|Icons' },
    // { name: 'Raster Image Import.gaml|main', code: 'Data/Data Importation/models/Raster Image Import.gaml|main' },
    // { name: 'SHP Import.gaml|GIS_agentification', code: 'Data/Data Importation/models/SHP Import.gaml|GIS_agentification' },
    // { name: 'URL Image Import.gaml|urlImage', code: 'Data/Data Importation/models/URL Image Import.gaml|urlImage' },
    // { name: 'Download Data (OSM-images).gaml|downloadGISdata', code: 'Data/Download Spatial Data/models/Download Data (OSM-images).gaml|downloadGISdata' },
    // { name: 'from GAMA CRS.gaml|ProjectionManagement', code: 'Data/Spatial Projection/models/from GAMA CRS.gaml|ProjectionManagement' },
    // { name: 'to GAMA CRS.gaml|ProjectionManagement', code: 'Data/Spatial Projection/models/to GAMA CRS.gaml|ProjectionManagement' },
    // { name: 'FileUtils.gaml|fileUtils', code: 'Data/Utils/models/FileUtils.gaml|fileUtils' },
    // { name: 'TestWebAddress.gaml|testWebAddress', code: 'Data/Utils/models/TestWebAddress.gaml|testWebAddress' },
    // { name: 'ZipUnzip.gaml|ZipUnzip', code: 'Data/Utils/models/ZipUnzip.gaml|ZipUnzip' },
    // { name: 'Rule Based Behaviors.gaml|Try it', code: 'GAML Syntax/Architectures/Rule Based Behaviors.gaml|Try it' },
    // { name: 'If Then Else.gaml|my_xp', code: 'GAML Syntax/Conditional Structures/If Then Else.gaml|my_xp' },
    // { name: 'State Transitions.gaml|dummy_xp', code: 'GAML Syntax/Conditional Structures/State Transitions.gaml|dummy_xp' },
    // { name: 'Switch And Match.gaml|Rock Paper Scissors', code: 'GAML Syntax/Conditional Structures/Switch And Match.gaml|Rock Paper Scissors' },
    // { name: 'When.gaml|my_xp', code: 'GAML Syntax/Conditional Structures/When.gaml|my_xp' },
    // { name: 'Casting.gaml|Casting', code: 'GAML Syntax/Data Types And Structures/Casting.gaml|Casting' },
    // { name: 'Date Type And Real Dates.gaml|main', code: 'GAML Syntax/Data Types And Structures/Date and Time/Date Type And Real Dates.gaml|main' },
    // { name: 'Simple Time Definition.gaml|SimpleTimedefinition', code: 'GAML Syntax/Data Types And Structures/Date and Time/Simple Time Definition.gaml|SimpleTimedefinition' },
    // { name: 'Fields.gaml|Fields', code: 'GAML Syntax/Data Types And Structures/Fields.gaml|Fields' },
    // { name: 'Graph.gaml|Graph', code: 'GAML Syntax/Data Types And Structures/Graph.gaml|Graph' },
    // { name: 'Lists.gaml|Lists', code: 'GAML Syntax/Data Types And Structures/Lists.gaml|Lists' },
    // { name: 'Maps.gaml|Maps', code: 'GAML Syntax/Data Types And Structures/Maps.gaml|Maps' },
    // { name: 'Matrices.gaml|Matrices', code: 'GAML Syntax/Data Types And Structures/Matrices.gaml|Matrices' },
    // { name: 'Units And Constants.gaml|exp', code: 'GAML Syntax/Data Types And Structures/Units And Constants.gaml|exp' },
    // { name: 'Ask Agents.gaml|name', code: 'GAML Syntax/Loop And Iterations/Ask Agents.gaml|name' },
    // { name: 'Iterators.gaml|exp', code: 'GAML Syntax/Loop And Iterations/Iterators.gaml|exp' },
    // { name: 'Loop Over.gaml|exp', code: 'GAML Syntax/Loop And Iterations/Loop Over.gaml|exp' },
    // { name: 'Loop Statement.gaml|name', code: 'GAML Syntax/Loop And Iterations/Loop Statement.gaml|name' },
    // { name: 'Default Scheduler.gaml|example_default_scheduler', code: 'GAML Syntax/Scheduler/Default Scheduler.gaml|example_default_scheduler' },
    // { name: 'No Scheduler.gaml|No Scheduling', code: 'GAML Syntax/Scheduler/No Scheduler.gaml|No Scheduling' },
    // { name: 'Not Executed Random Manager Scheduler.gaml|Schedule', code: 'GAML Syntax/Scheduler/Not Executed Random Manager Scheduler.gaml|Schedule' },
    // { name: 'Random Scheduler.gaml|Schedule', code: 'GAML Syntax/Scheduler/Random Scheduler.gaml|Schedule' },
    // { name: 'Species Manager.gaml|Schedule', code: 'GAML Syntax/Scheduler/Species Manager.gaml|Schedule' },
    // { name: 'Init Action.gaml|InitAction', code: 'GAML Syntax/Simulation Initialization/Init Action.gaml|InitAction' },
    // { name: 'Attribute access.gaml|Attributeaccess', code: 'GAML Syntax/Species Definition/Attribute access.gaml|Attributeaccess' },
    // { name: 'Inheritance.gaml|Run', code: 'GAML Syntax/Species Definition/Inheritance.gaml|Run' },
    // { name: 'Mirror species - creation and death of agents.gaml|mirroExp', code: 'GAML Syntax/Species Definition/Mirror species - creation and death of agents.gaml|mirroExp' },
    // { name: 'Mirror species.gaml|mirroExp', code: 'GAML Syntax/Species Definition/Mirror species.gaml|mirroExp' },
    // { name: 'Benchmarking.gaml|Benchmarking', code: 'GAML Syntax/System/Benchmarking.gaml|Benchmarking' },
    // { name: 'Errors.gaml|Raise a normal warning', code: 'GAML Syntax/System/Errors.gaml|Raise a normal warning' },
    // { name: 'Preferences.gaml|Display Preferences', code: 'GAML Syntax/System/Preferences.gaml|Display Preferences' },
    // { name: 'Syntax (1.6).gaml|exp1', code: 'GAML Syntax/System/Syntax (1.6).gaml|exp1' },
    // { name: 'System.gaml|Run', code: 'GAML Syntax/System/System.gaml|Run' },
    // { name: 'Basic Example.gaml|***new', code: 'GAML Syntax/Unit Test/Basic Example.gaml|***new' },
    // { name: 'Experiment Example.experiment|Test Experiment', code: 'GAML Syntax/Unit Test/Experiment Example.experiment|Test Experiment' },
    // { name: 'Two Species (Example).gaml|***new', code: 'GAML Syntax/Unit Test/Two Species (Example).gaml|***new' },
    // { name: 'Declaration of Parameters.gaml|Show Parameters', code: 'GAML Syntax/Variables/Declaration of Parameters.gaml|Show Parameters' },
    // { name: 'Notifying Variables.gaml|Notification', code: 'GAML Syntax/Variables/Notifying Variables.gaml|Notification' },
    // { name: 'Batch.gaml|Simple', code: 'Model Exploration/Batch Simulation/Batch.gaml|Simple' },
    // { name: 'Experiment and simulation.gaml|basic_exp', code: 'Model Exploration/Experiment species/Experiment and simulation.gaml|basic_exp' },
    // { name: 'Multi-simulation.gaml|main', code: 'Model Exploration/Multi-simulation/Multi-simulation.gaml|main' },
    // { name: 'Ants Adapter.gaml|Base', code: 'Modeling/Model Coupling/Co-AntPreyPredator/Ants Adapter.gaml|Base' },
    // { name: 'Comodel Example (Mixed Behaviors).gaml|main', code: 'Modeling/Model Coupling/Co-AntPreyPredator/Comodel Example (Mixed Behaviors).gaml|main' },
    // { name: 'Comodel Example (Populations Mutated).gaml|main', code: 'Modeling/Model Coupling/Co-PreyPredator/Comodel Example (Populations Mutated).gaml|main' },
    // { name: 'Prey Predator Adapter.gaml|Simple', code: 'Modeling/Model Coupling/Co-PreyPredator/Prey Predator Adapter.gaml|Simple' },
    // { name: 'Prey Predator.gaml|Prey Predator Exp', code: 'Modeling/Model Coupling/Co-PreyPredator/Prey Predator.gaml|Prey Predator Exp' },
    // { name: 'Flies Adapter.gaml|Simple', code: 'Modeling/Model Coupling/Flies and Mosquitos/Adapters/Flies Adapter.gaml|Simple' },
    // { name: 'Mosquitos Adapter.gaml|Generic', code: 'Modeling/Model Coupling/Flies and Mosquitos/Adapters/Mosquitos Adapter.gaml|Generic' },
    // { name: 'Create and kill models.gaml|main', code: 'Modeling/Model Coupling/Flies and Mosquitos/Create and kill models.gaml|main' },
    // { name: 'Flies.gaml|Simple', code: 'Modeling/Model Coupling/Flies and Mosquitos/Models/Flies.gaml|Simple' },
    // { name: 'Mosquitos.gaml|Generic', code: 'Modeling/Model Coupling/Flies and Mosquitos/Models/Mosquitos.gaml|Generic' },
    // { name: 'Simple GUI comodel.gaml|Complex', code: 'Modeling/Model Coupling/Flies and Mosquitos/Simple GUI comodel.gaml|Complex' },
    { name: 'Balls, Groups and Clouds.gaml|cloud_experiment', code: 'Modeling/Multi-Level Usage/Balls, Groups and Clouds.gaml|cloud_experiment' },
    { name: 'Corridor (Hybrid vs ABM).gaml|default_experiment', code: 'Modeling/Multi-Level Usage/Corridor (Hybrid vs ABM).gaml|default_experiment' },
    { name: 'Corridor.gaml|Corridor', code: 'Modeling/Multi-Level Usage/Corridor.gaml|Corridor' },
    { name: 'Predators, Preys and Shelters.gaml|default_experiment', code: 'Modeling/Multi-Level Usage/Predators, Preys and Shelters.gaml|default_experiment' },
    { name: 'Multi-thread.gaml|multithread', code: 'Modeling/Multi-thread simulation/Multi-thread.gaml|multithread' },
    { name: 'Continuous Field of Vision.gaml|fieldofvision', code: 'Modeling/Spatial Topology/Agent movement/models/Continuous Field of Vision.gaml|fieldofvision' },
    { name: 'Follow Path.gaml|main', code: 'Modeling/Spatial Topology/Agent movement/models/Follow Path.gaml|main' },
    { name: 'Follow Weighted Network (Agents).gaml|weightperagents', code: 'Modeling/Spatial Topology/Agent movement/models/Follow Weighted Network (Agents).gaml|weightperagents' },
    { name: 'Goto Directed Graph.gaml|simplemodel', code: 'Modeling/Spatial Topology/Agent movement/models/Goto Directed Graph.gaml|simplemodel' },
    { name: 'Goto Grid Weights.gaml|goto_grid', code: 'Modeling/Spatial Topology/Agent movement/models/Goto Grid Weights.gaml|goto_grid' },
    { name: 'Goto Grid.gaml|goto_grid', code: 'Modeling/Spatial Topology/Agent movement/models/Goto Grid.gaml|goto_grid' },
    { name: 'Goto Network.gaml|goto_network', code: 'Modeling/Spatial Topology/Agent movement/models/Goto Network.gaml|goto_network' },
    { name: 'Goto Polygon.gaml|goto_polygon', code: 'Modeling/Spatial Topology/Agent movement/models/Goto Polygon.gaml|goto_polygon' },
    { name: 'Moving3D.gaml|Moving', code: 'Modeling/Spatial Topology/Agent movement/models/Moving3D.gaml|Moving' },
    { name: 'Wander on Graph.gaml|WanderonGraph', code: 'Modeling/Spatial Topology/Agent movement/models/Wander on Graph.gaml|WanderonGraph' },
    { name: 'Accessing Fields.gaml|Show', code: 'Modeling/Spatial Topology/Fields/Accessing Fields.gaml|Show' },
    { name: '3D Graph.gaml|Display', code: 'Modeling/Spatial Topology/Graphs/models/3D Graph.gaml|Display' },
    { name: 'Classic Graph Generation.gaml|loadgraph', code: 'Modeling/Spatial Topology/Graphs/models/Classic Graph Generation.gaml|loadgraph' },
    { name: 'Clustering.gaml|clustering', code: 'Modeling/Spatial Topology/Graphs/models/Clustering.gaml|clustering' },
    { name: 'Graph Building From Agents.gaml|loadgraph', code: 'Modeling/Spatial Topology/Graphs/models/Graph Building From Agents.gaml|loadgraph' },
    { name: 'Graph Loading Layout.gaml|loadgraph', code: 'Modeling/Spatial Topology/Graphs/models/Graph Loading Layout.gaml|loadgraph' },
    { name: 'Graph Operators.gaml|graphoperators', code: 'Modeling/Spatial Topology/Graphs/models/Graph Operators.gaml|graphoperators' },
    { name: 'Hand Made Graph.gaml|create_graph', code: 'Modeling/Spatial Topology/Graphs/models/Hand Made Graph.gaml|create_graph' },
    { name: 'Multigraph.gaml|multigraph', code: 'Modeling/Spatial Topology/Graphs/models/Multigraph.gaml|multigraph' },
    { name: 'Shortest paths.gaml|goto_network', code: 'Modeling/Spatial Topology/Graphs/models/Shortest paths.gaml|goto_network' },
    { name: 'Strahler.gaml|testStrahler', code: 'Modeling/Spatial Topology/Graphs/models/Strahler.gaml|testStrahler' },
    { name: 'Hexagonal Grid.gaml|hexagonal', code: 'Modeling/Spatial Topology/Grids/models/Hexagonal Grid.gaml|hexagonal' },
    { name: 'Shortest Path on Grid.gaml|goto_grid', code: 'Modeling/Spatial Topology/Grids/models/Shortest Path on Grid.gaml|goto_grid' },
    { name: 'Weighted Shortest Path on Grid.gaml|goto_grid', code: 'Modeling/Spatial Topology/Grids/models/Weighted Shortest Path on Grid.gaml|goto_grid' },
    { name: 'Geometry Discretization.gaml|to_squares', code: 'Modeling/Spatial Topology/Spatial Operators/models/Geometry Discretization.gaml|to_squares' },
    { name: 'Moran Index.gaml|Moran', code: 'Modeling/Spatial Topology/Spatial Operators/models/Moran Index.gaml|Moran' },
    { name: 'Simplification and Buffer.gaml|Simplify this !', code: 'Modeling/Spatial Topology/Spatial Operators/models/Simplification and Buffer.gaml|Simplify this !' },
    { name: 'Spatial Interpolation.gaml|spatialinterpolation', code: 'Modeling/Spatial Topology/Spatial Operators/models/Spatial Interpolation.gaml|spatialinterpolation' },
    { name: 'Spatial Operators (Examples).gaml|example_spatial_operators', code: 'Modeling/Spatial Topology/Spatial Operators/models/Spatial Operators (Examples).gaml|example_spatial_operators' },
    { name: 'Spatial Queries.gaml|Spatialqueries', code: 'Modeling/Spatial Topology/Spatial Operators/models/Spatial Queries.gaml|Spatialqueries' },
    { name: 'Topologies.gaml|topology_test', code: 'Modeling/Spatial Topology/Spatial Operators/models/Topologies.gaml|topology_test' },
    { name: 'Multicriteria Decision.gaml|multicriteria', code: 'Modeling/Specific Operators/Multicriteria Decision.gaml|multicriteria' },
    { name: 'Ant Foraging.gaml|With Inspector', code: 'Toy Models/Ants (Foraging and Sorting)/models/Ant Foraging.gaml|With Inspector' },
    { name: 'Ant Sorting.gaml|Color sort', code: 'Toy Models/Ants (Foraging and Sorting)/models/Ant Sorting.gaml|Color sort' },
    { name: 'GAMA 1.8.gaml|Run me !', code: 'Toy Models/Art/Gama 1.8/models/GAMA 1.8.gaml|Run me !' },
    { name: 'Tree and Seasons.gaml|Random', code: 'Toy Models/Art/L-Trees/models/Tree and Seasons.gaml|Random' },
    { name: 'Mondrian City.gaml|MondrianCity', code: 'Toy Models/Art/Mondrian City/models/Mondrian City.gaml|MondrianCity' },
    { name: 'Mondrian Generator.gaml|MondrianGenerator', code: 'Toy Models/Art/Mondrian City/models/Mondrian Generator.gaml|MondrianGenerator' },
    { name: 'Radiohead In Point Coud.gaml|OK_Computer', code: 'Toy Models/Art/Radiohead In Point Cloud/models/Radiohead In Point Coud.gaml|OK_Computer' },
    { name: 'Voronoi.gaml|voronoi', code: 'Toy Models/Art/Voronoi/Voronoi.gaml|voronoi' },
    { name: 'Boids 3D Analysis.gaml|Simple', code: 'Toy Models/Boids/models/Boids 3D Analysis.gaml|Simple' },
    { name: 'Boids 3D Motion.gaml|3D', code: 'Toy Models/Boids/models/Boids 3D Motion.gaml|3D' },
    { name: 'Boids With Flocks.gaml|boids_flocks', code: 'Toy Models/Boids/models/Boids With Flocks.gaml|boids_flocks' },
    { name: 'Boids.gaml|Basic', code: 'Toy Models/Boids/models/Boids.gaml|Basic' },
    { name: 'Bubble Sort 3D.gaml|Display', code: 'Toy Models/Bubble Sort/models/Bubble Sort 3D.gaml|Display' },
    { name: 'Circle.gaml|main', code: 'Toy Models/Circle/Circle.gaml|main' },
    { name: 'Clock.gaml|Display', code: 'Toy Models/Clock/models/Clock.gaml|Display' },
    // { name: 'Boids Adapter.gaml|Adapter', code: 'Toy Models/Comodels/Boids and Voronoi/Adapters/Boids Adapter.gaml|Adapter' },
    // { name: 'Voronoi Adapter.gaml|Adapter 2', code: 'Toy Models/Comodels/Boids and Voronoi/Adapters/Voronoi Adapter.gaml|Adapter 2' },
    // { name: 'Voroboids (Boids and Voronoi Comodel).gaml|main', code: 'Toy Models/Comodels/Boids and Voronoi/Voroboids (Boids and Voronoi Comodel).gaml|main' },
    // { name: 'Boids Adapter.gaml|Adapter of Boids', code: 'Toy Models/Comodels/City Boids/Adapters/Boids Adapter.gaml|Adapter of Boids' },
    // { name: 'Procedural City Adapter.gaml|Adapter', code: 'Toy Models/Comodels/City Boids/Adapters/Procedural City Adapter.gaml|Adapter' },
    // { name: 'City Boids Comodel.gaml|main', code: 'Toy Models/Comodels/City Boids/City Boids Comodel.gaml|main' },
    // { name: 'Evacuation Adapter.gaml|Adapter of Evacuation', code: 'Toy Models/Comodels/Flood and Evacuation/Adapters/Evacuation Adapter.gaml|Adapter of Evacuation' },
    // { name: 'Flood Adapter.gaml|Adapter', code: 'Toy Models/Comodels/Flood and Evacuation/Adapters/Flood Adapter.gaml|Adapter' },
    // { name: 'Flood Evacuation Comodel.gaml|simple', code: 'Toy Models/Comodels/Flood and Evacuation/Flood Evacuation Comodel.gaml|simple' },
    // { name: 'Comodel 0.gaml|coModel', code: 'Toy Models/Comodels/Plant Growth and Weather/Comodel 0.gaml|coModel' },
    // { name: 'Comodel 1.gaml|CoModel', code: 'Toy Models/Comodels/Plant Growth and Weather/Comodel 1.gaml|CoModel' },
    // { name: 'Comodel 2.gaml|CoModel', code: 'Toy Models/Comodels/Plant Growth and Weather/Comodel 2.gaml|CoModel' },
    // { name: 'Plant Growth Adapter.gaml|Adapter', code: 'Toy Models/Comodels/Plant Growth and Weather/Plant Growth Adapter.gaml|Adapter' },
    // { name: 'Plant Growth.gaml|Plant Growth', code: 'Toy Models/Comodels/Plant Growth and Weather/Plant Growth.gaml|Plant Growth' },
    // { name: 'Weather.gaml|Weather', code: 'Toy Models/Comodels/Plant Growth and Weather/Weather.gaml|Weather' },
    // { name: 'Predator Prey Adapter.gaml|Adapter2', code: 'Toy Models/Comodels/Prey Sugarscaptor/Adapters/Predator Prey Adapter.gaml|Adapter2' },
    // { name: 'Sugarscape Adapter.gaml|Adapter', code: 'Toy Models/Comodels/Prey Sugarscaptor/Adapters/Sugarscape Adapter.gaml|Adapter' },
    // { name: 'Prey Sugarscaptor Comodel.gaml|main', code: 'Toy Models/Comodels/Prey Sugarscaptor/Prey Sugarscaptor Comodel.gaml|main' },
    // { name: 'ABM Adapter.gaml|Adapter', code: 'Toy Models/Comodels/SIR Switch/Legacy_models/ABM Adapter.gaml|Adapter' },
    // { name: 'EBM Adapter.gaml|Adapter', code: 'Toy Models/Comodels/SIR Switch/Legacy_models/EBM Adapter.gaml|Adapter' },
    // { name: 'SIR_ABM.gaml|SIR_ABM_exp', code: 'Toy Models/Comodels/SIR Switch/Legacy_models/SIR_ABM.gaml|SIR_ABM_exp' },
    // { name: 'SIR_EBM.gaml|SIR_EBM_exp', code: 'Toy Models/Comodels/SIR Switch/Legacy_models/SIR_EBM.gaml|SIR_EBM_exp' },
    // { name: 'SIR Comodel.gaml|Simple_exp', code: 'Toy Models/Comodels/SIR Switch/SIR Comodel.gaml|Simple_exp' },
    // { name: 'Traffic Adapter.gaml|Adapter of Traffice', code: 'Toy Models/Comodels/Urban and Traffic/Adapters/Traffic Adapter.gaml|Adapter of Traffice' },
    // { name: 'Urban Adapter.gaml|Adapter', code: 'Toy Models/Comodels/Urban and Traffic/Adapters/Urban Adapter.gaml|Adapter' },
    // { name: 'Urbanization And Traffic Comodel.gaml|main', code: 'Toy Models/Comodels/Urban and Traffic/Urbanization And Traffic Comodel.gaml|main' },
    { name: 'SIR (ABM vs EBM).gaml|Simulation_ABM_EBM', code: 'Toy Models/Epidemiology/models/SIR (ABM vs EBM).gaml|Simulation_ABM_EBM' },
    { name: 'SIR (Split in Agents).gaml|Simulation', code: 'Toy Models/Epidemiology/models/SIR (Split in Agents).gaml|Simulation' },
    { name: 'SIR (Switch).gaml|mysimulation', code: 'Toy Models/Epidemiology/models/SIR (Switch).gaml|mysimulation' },
    { name: 'Susceptible Infected (SI).gaml|Simulation', code: 'Toy Models/Epidemiology/models/Susceptible Infected (SI).gaml|Simulation' },
    { name: 'Susceptible Infected Recovered (SIR).gaml|Simulation', code: 'Toy Models/Epidemiology/models/Susceptible Infected Recovered (SIR).gaml|Simulation' },
    { name: 'City Escape.gaml|Run', code: 'Toy Models/Evacuation/models/City Escape.gaml|Run' },
    { name: 'Continuous Move.gaml|main', code: 'Toy Models/Evacuation/models/Continuous Move.gaml|main' },
    { name: 'Goto on Grid.gaml|evacuationgoto', code: 'Toy Models/Evacuation/models/Goto on Grid.gaml|evacuationgoto' },
    { name: 'Move on Grid.gaml|Run', code: 'Toy Models/Evacuation/models/Move on Grid.gaml|Run' },
    { name: 'Hydrological Model.gaml|Run', code: 'Toy Models/Flood Simulation/models/Hydrological Model.gaml|Run' },
    { name: 'Mas KMeans Interactive.gaml|clustering2D', code: 'Toy Models/Learning/models/Mas KMeans Interactive.gaml|clustering2D' },
    { name: 'Mas KMeans.gaml|clustering2D', code: 'Toy Models/Learning/models/Mas KMeans.gaml|clustering2D' },
    { name: 'Life.gaml|Game of Life', code: 'Toy Models/Life/Life.gaml|Game of Life' },
    { name: 'Common Bug Species.gaml|', code: 'Toy Models/Multi-level Data Analysis/includes/Common Bug Species.gaml|' },
    { name: 'Graph From Bug (Distance Graph).gaml|spatialGraph', code: 'Toy Models/Multi-level Data Analysis/models/Graph From Bug (Distance Graph).gaml|spatialGraph' },
    { name: 'Graph From Bug (Mirror Graph).gaml|AdvancedView', code: 'Toy Models/Multi-level Data Analysis/models/Graph From Bug (Mirror Graph).gaml|AdvancedView' },
    { name: 'MODAVI.gaml|MODAVI', code: 'Toy Models/Multi-level Data Analysis/models/MODAVI.gaml|MODAVI' },
    { name: 'Lotka-Volterra (Influence of Integration Step).gaml|maths', code: 'Toy Models/Predator Prey/Lotka-Volterra (Influence of Integration Step).gaml|maths' },
    { name: 'Lotka-Volterra (Simple).gaml|maths', code: 'Toy Models/Predator Prey/Lotka-Volterra (Simple).gaml|maths' },
    { name: 'Common Schelling Segregation.gaml|', code: 'Toy Models/Segregation (Schelling)/include/Common Schelling Segregation.gaml|' },
    { name: 'Segregation (Agents).gaml|schelling', code: 'Toy Models/Segregation (Schelling)/models/Segregation (Agents).gaml|schelling' },
    { name: 'Segregation (Cellular Automata).gaml|schelling', code: 'Toy Models/Segregation (Schelling)/models/Segregation (Cellular Automata).gaml|schelling' },
    { name: 'Segregation (GIS).gaml|schelling', code: 'Toy Models/Segregation (Schelling)/models/Segregation (GIS).gaml|schelling' },
    { name: 'Segregation (Google Map).gaml|schelling', code: 'Toy Models/Segregation (Schelling)/models/Segregation (Google Map).gaml|schelling' },
    { name: 'Soccer Base.gaml|', code: 'Toy Models/Soccer/models/Soccer Base.gaml|' },
    { name: 'Soccer Experiments.gaml|intelligentTeam_vs_stupidTeam', code: 'Toy Models/Soccer/models/Soccer Experiments.gaml|intelligentTeam_vs_stupidTeam' },
    { name: 'Soccer.gaml|match', code: 'Toy Models/Soccer/models/Soccer.gaml|match' },
    { name: 'Team1 Strategy.gaml|', code: 'Toy Models/Soccer/models/Team1 Strategy.gaml|' },
    { name: 'Team2 Strategy.gaml|', code: 'Toy Models/Soccer/models/Team2 Strategy.gaml|' },
    { name: 'Sugarscape.gaml|sugarscape', code: 'Toy Models/Sugarscape/models/Sugarscape.gaml|sugarscape' },
    { name: 'LWR Traffic Flow Model.gaml|TraficGroup', code: 'Toy Models/Traffic/models/LWR Traffic Flow Model.gaml|TraficGroup' },
    { name: 'Netlogo - Traffic model - 1 road.gaml|NetlogoTrafficmodel', code: 'Toy Models/Traffic/models/Netlogo - Traffic model - 1 road.gaml|NetlogoTrafficmodel' },
    { name: 'Netlogo - Traffic model - 2 roads.gaml|NetlogoTrafficmodel', code: 'Toy Models/Traffic/models/Netlogo - Traffic model - 2 roads.gaml|NetlogoTrafficmodel' },
    { name: 'Simple Traffic Model.gaml|traffic', code: 'Toy Models/Traffic/models/Simple Traffic Model.gaml|traffic' },
    { name: 'Raster Urban Growth.gaml|raster', code: 'Toy Models/Urban Growth/models/Raster Urban Growth.gaml|raster' },
    { name: 'Vote.gaml|vote', code: 'Toy Models/Vote/Vote.gaml|vote' },
    { name: 'Waterflow Field Elevation.gaml|hydro', code: 'Toy Models/Waterflow/models/Waterflow Field Elevation.gaml|hydro' },
    { name: 'Waterflow Grid Elevation.gaml|hydro', code: 'Toy Models/Waterflow/models/Waterflow Grid Elevation.gaml|hydro' },
    { name: 'Waterflow Grid Neighborhood.gaml|Waterflowgridneighborhood', code: 'Toy Models/Waterflow/models/Waterflow Grid Neighborhood.gaml|Waterflowgridneighborhood' },
    { name: 'Waterflow River Graph.gaml|flow', code: 'Toy Models/Waterflow/models/Waterflow River Graph.gaml|flow' },
    { name: 'Waterflow River Water Unit.gaml|flow', code: 'Toy Models/Waterflow/models/Waterflow River Water Unit.gaml|flow' },
    { name: 'Waterflow Watershed.gaml|waterFlow', code: 'Toy Models/Waterflow/models/Waterflow Watershed.gaml|waterFlow' },
    { name: 'Model 01.gaml|Tuto3D', code: 'Tutorials/3D/models/Model 01.gaml|Tuto3D' },
    { name: 'Model 02.gaml|Tuto3D', code: 'Tutorials/3D/models/Model 02.gaml|Tuto3D' },
    { name: 'Model 03.gaml|Tuto3D', code: 'Tutorials/3D/models/Model 03.gaml|Tuto3D' },
    { name: 'Incremental Model 1.gaml|main_experiment', code: 'Tutorials/Incremental Model/models/Incremental Model 1.gaml|main_experiment' },
    { name: 'Incremental Model 2.gaml|main_experiment', code: 'Tutorials/Incremental Model/models/Incremental Model 2.gaml|main_experiment' },
    { name: 'Incremental Model 3.gaml|main_experiment', code: 'Tutorials/Incremental Model/models/Incremental Model 3.gaml|main_experiment' },
    { name: 'Incremental Model 4.gaml|main_experiment', code: 'Tutorials/Incremental Model/models/Incremental Model 4.gaml|main_experiment' },
    { name: 'Incremental Model 5.gaml|main_experiment', code: 'Tutorials/Incremental Model/models/Incremental Model 5.gaml|main_experiment' },
    { name: 'Incremental Model 6.gaml|main_experiment', code: 'Tutorials/Incremental Model/models/Incremental Model 6.gaml|main_experiment' },
    { name: 'Incremental Model 7.gaml|main_experiment', code: 'Tutorials/Incremental Model/models/Incremental Model 7.gaml|main_experiment' },
    { name: 'model1.gaml|main', code: 'Tutorials/Luneray flu/models/model1.gaml|main' },
    { name: 'model2.gaml|main', code: 'Tutorials/Luneray flu/models/model2.gaml|main' },
    { name: 'model3.gaml|main', code: 'Tutorials/Luneray flu/models/model3.gaml|main' },
    { name: 'model4.gaml|main', code: 'Tutorials/Luneray flu/models/model4.gaml|main' },
    { name: 'model5.gaml|main', code: 'Tutorials/Luneray flu/models/model5.gaml|main' },
    { name: 'model6.gaml|main', code: 'Tutorials/Luneray flu/models/model6.gaml|main' },
    { name: 'Model 01.gaml|prey_predator', code: 'Tutorials/Predator Prey/models/Model 01.gaml|prey_predator' },
    { name: 'Model 02.gaml|prey_predator', code: 'Tutorials/Predator Prey/models/Model 02.gaml|prey_predator' },
    { name: 'Model 03.gaml|prey_predator', code: 'Tutorials/Predator Prey/models/Model 03.gaml|prey_predator' },
    { name: 'Model 04.gaml|prey_predator', code: 'Tutorials/Predator Prey/models/Model 04.gaml|prey_predator' },
    { name: 'Model 05.gaml|prey_predator', code: 'Tutorials/Predator Prey/models/Model 05.gaml|prey_predator' },
    { name: 'Model 06.gaml|prey_predator', code: 'Tutorials/Predator Prey/models/Model 06.gaml|prey_predator' },
    { name: 'Model 07.gaml|prey_predator', code: 'Tutorials/Predator Prey/models/Model 07.gaml|prey_predator' },
    { name: 'Model 08.gaml|prey_predator', code: 'Tutorials/Predator Prey/models/Model 08.gaml|prey_predator' },
    { name: 'Model 09.gaml|prey_predator', code: 'Tutorials/Predator Prey/models/Model 09.gaml|prey_predator' },
    { name: 'Model 10.gaml|prey_predator', code: 'Tutorials/Predator Prey/models/Model 10.gaml|prey_predator' },
    { name: 'Model 11.gaml|prey_predator', code: 'Tutorials/Predator Prey/models/Model 11.gaml|prey_predator' },
    { name: 'Model 12.gaml|prey_predator', code: 'Tutorials/Predator Prey/models/Model 12.gaml|prey_predator' },
    { name: 'Model 13.gaml|prey_predator', code: 'Tutorials/Predator Prey/models/Model 13.gaml|prey_predator' },
    { name: 'Model 01.gaml|road_traffic', code: 'Tutorials/Road Traffic/models/Model 01.gaml|road_traffic' },
    { name: 'Model 02.gaml|road_traffic', code: 'Tutorials/Road Traffic/models/Model 02.gaml|road_traffic' },
    { name: 'Model 03.gaml|road_traffic', code: 'Tutorials/Road Traffic/models/Model 03.gaml|road_traffic' },
    { name: 'Model 04.gaml|road_traffic', code: 'Tutorials/Road Traffic/models/Model 04.gaml|road_traffic' },
    { name: 'Model 05.gaml|road_traffic', code: 'Tutorials/Road Traffic/models/Model 05.gaml|road_traffic' },
    { name: 'Model 06.gaml|road_traffic', code: 'Tutorials/Road Traffic/models/Model 06.gaml|road_traffic' },
    { name: 'Model 07.gaml|road_traffic', code: 'Tutorials/Road Traffic/models/Model 07.gaml|road_traffic' },
    // { name: 'Parameters and Commands.gaml|Show Parameters', code: 'Visualization and User Interaction/GUI Design/Parameters and Commands.gaml|Show Parameters' },
    // { name: 'Confirm Dialog.gaml|Confirmdialog_example', code: 'Visualization and User Interaction/User Interaction/models/Confirm Dialog.gaml|Confirmdialog_example' },
    // { name: 'Event Layer.gaml|Displays', code: 'Visualization and User Interaction/User Interaction/models/Event Layer.gaml|Displays' },
    // { name: 'Mouse Exit and Enter.gaml|Run', code: 'Visualization and User Interaction/User Interaction/models/Mouse Exit and Enter.gaml|Run' },
    // { name: 'Moving Agents.gaml|Click and Move', code: 'Visualization and User Interaction/User Interaction/models/Moving Agents.gaml|Click and Move' },
    // { name: 'Tools Panel.gaml|ToolsPanel', code: 'Visualization and User Interaction/User Interaction/models/Tools Panel.gaml|ToolsPanel' },
    // { name: 'User Command.gaml|Displays', code: 'Visualization and User Interaction/User Interaction/models/User Command.gaml|Displays' },
    // { name: 'User Control Architecture.gaml|Displays', code: 'Visualization and User Interaction/User Interaction/models/User Control Architecture.gaml|Displays' },
    // { name: 'User input.gaml|UserInputdialog_example', code: 'Visualization and User Interaction/User Interaction/models/User input.gaml|UserInputdialog_example' },
    // { name: 'User Pause and Resume.gaml|Try Me !', code: 'Visualization and User Interaction/User Interaction/models/User Pause and Resume.gaml|Try Me !' },
    // { name: 'Wizard.gaml|Wizard_example', code: 'Visualization and User Interaction/User Interaction/models/Wizard.gaml|Wizard_example' },
    // { name: 'Building Elevation.gaml|Road Traffic', code: 'Visualization and User Interaction/Visualization/3D Visualization/models/Building Elevation.gaml|Road Traffic' },
    // { name: 'Built-In Shapes.gaml|3D Shapes', code: 'Visualization and User Interaction/Visualization/3D Visualization/models/Built-In Shapes.gaml|3D Shapes' },
    // { name: 'Camera Definitions.gaml|Display', code: 'Visualization and User Interaction/Visualization/3D Visualization/models/Camera Definitions.gaml|Display' },
    // { name: 'Camera Shared Zoom.experiment|Shared Zoom Example', code: 'Visualization and User Interaction/Visualization/3D Visualization/models/Camera Shared Zoom.experiment|Shared Zoom Example' },
    // { name: 'GIS Visualization.gaml|GIS_visualization', code: 'Visualization and User Interaction/Visualization/3D Visualization/models/GIS Visualization.gaml|GIS_visualization' },
    // { name: 'Lighting.gaml|Display', code: 'Visualization and User Interaction/Visualization/3D Visualization/models/Lighting.gaml|Display' },
    // { name: 'Moving 3D Object.gaml|Display', code: 'Visualization and User Interaction/Visualization/3D Visualization/models/Moving 3D Object.gaml|Display' },
    // { name: 'Procedural City.gaml|DisplayTextured', code: 'Visualization and User Interaction/Visualization/3D Visualization/models/Procedural City.gaml|DisplayTextured' },
    // { name: 'Specular Effects.gaml|specular_light', code: 'Visualization and User Interaction/Visualization/3D Visualization/models/Specular Effects.gaml|specular_light' },
    // { name: 'Aspects.gaml|expe', code: 'Visualization and User Interaction/Visualization/Aspects.gaml|expe' },
    // { name: 'Building Heatmap.gaml|Show heatmap', code: 'Visualization and User Interaction/Visualization/Building Heatmap.gaml|Show heatmap' },
    // { name: 'Ant Foraging (Charts examples).gaml|Experiment', code: 'Visualization and User Interaction/Visualization/Charts/models/Ant Foraging (Charts examples).gaml|Experiment' },
    // { name: 'Bar.gaml|Multiple displays', code: 'Visualization and User Interaction/Visualization/Charts/models/Bar.gaml|Multiple displays' },
    // { name: 'Distribution.gaml|Example of Distribution', code: 'Visualization and User Interaction/Visualization/Charts/models/Distribution.gaml|Example of Distribution' },
    // { name: 'Heatmap.gaml|Different heatmaps', code: 'Visualization and User Interaction/Visualization/Charts/models/Heatmap.gaml|Different heatmaps' },
    // { name: 'Long Series.gaml|Long series', code: 'Visualization and User Interaction/Visualization/Charts/models/Long Series.gaml|Long series' },
    // { name: 'Pie.gaml|Different Pies', code: 'Visualization and User Interaction/Visualization/Charts/models/Pie.gaml|Different Pies' },
    // { name: 'Radar.gaml|Different radars', code: 'Visualization and User Interaction/Visualization/Charts/models/Radar.gaml|Different radars' },
    // { name: 'Series.gaml|Different series', code: 'Visualization and User Interaction/Visualization/Charts/models/Series.gaml|Different series' },
    // { name: 'XY.gaml|main', code: 'Visualization and User Interaction/Visualization/Charts/models/XY.gaml|main' },
    // { name: 'Color Brewer.gaml|BrewerPalette', code: 'Visualization and User Interaction/Visualization/Color Brewer.gaml|BrewerPalette' },
    // { name: 'DEM Generator.gaml|Terrain', code: 'Visualization and User Interaction/Visualization/DEM Generator.gaml|Terrain' },
    // { name: 'Legend - Overlay.gaml|overlay', code: 'Visualization and User Interaction/Visualization/Legend - Overlay.gaml|overlay' },
    // { name: 'Palettes and Gradients.gaml|Palettes', code: 'Visualization and User Interaction/Visualization/Palettes and Gradients.gaml|Palettes' },
    // { name: 'Text Display.gaml|Strings', code: 'Visualization and User Interaction/Visualization/Text Display.gaml|Strings' },
    // { name: 'Worm Heatmap.gaml|Show heatmap', code: 'Visualization and User Interaction/Visualization/Worm Heatmap.gaml|Show heatmap' },
];