version: "3"

services:
  webapp:
    image: gamaweb/ui:alpha
    build: .
    restart: unless-stopped
    networks:
      - gamaweb
    env_file: .env
    ports:
      - "8080:80"

  gama:
    image: gamaplatform/mini:alpha
    container_name: gamamini
    restart: unless-stopped
    networks:
      - gamaweb
    ports:
      - "6868:6868" 
    command: -socket 6868
    # volumes:
    #   - ./comokit-model:/usr/lib/gama/headless/comokit

networks:
  gamaweb:
