# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: PypI Release Package

on:
  workflow_dispatch: # For manual trigger
    inputs:
      BUMP_VERSION_NUMBER:
        description: "Version number to bump to (if empty, publish with git number)"
        required: false
        default: ""
        type: string

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Bump package version
        if: "${{ inputs.BUMP_VERSION_NUMBER != '' }}"
        working-directory: ./python
        run: sed "s/^version =.*/version = \"${{ inputs.BUMP_VERSION_NUMBER }}\"/g" ./pyproject.toml


      - name: Build release distributions
        working-directory: ./python
        run: |
          python -m pip install build twine
          python -m build

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ${{ github.workspace }}/python/dist/

      - name: Bump package version
        if: "${{ inputs.BUMP_VERSION_NUMBER != '' }}"
        working-directory: ./python
        run: |
          git config --global user.email "my.gama.bot@gmail.com"
          git config --global user.name "GAMA Bot"
          git remote set-url origin https://gama-bot:$BOT_TOKEN@github.com/gama-platform/gama.clients.git
          git add ./pyproject.toml
          git commit -m "Bump package version"
          git push
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}